backend:
  name: git-gateway
  branch: master
  repo: coltborg/progatsby2-tut-blog
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
display_url: https://wonderful-bassi-206253.netlify.com
logo_url: https://wonderful-bassi-206253.netlify.com//static/logo-7665f742d9402c726ad0cd313e098ef8.svg
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title-YYYY-MM-DD.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Contact"
        name: "contact"
        file: "src/custom/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "Contact"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Email", name: "email", widget: "string", required: false, pattern: ['/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/', "Must have a valid email", ]
}